class_name AudioDirector
extends Node
## Buses (Master > Music, SFX), pooled one-shot SFX with pitch variance, and zone music/ambience beds that
## crossfade. SFX bus has a reverb whose room size follows the zone; Music bus gets a low-pass while paused.
## All audio is generated by assets/audio/gen_audio.py.

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const SFX_NAMES := ["jump", "land", "coin", "blue_coin", "key", "key_expired", "portal", "death", "respawn",
	"crown", "gravity", "ui_move", "ui_select", "title_hit", "zone", "trial"]
const BEDS := ["title", "surface", "cave", "hell", "corruption", "ice", "lake", "veil_title", "day", "falls", "temple"]
## Per-bed trim (dB) so beds sit at similar loudness.
const BED_GAIN := {&"temple": -3.5, &"falls": -1.0}
const PIANO_DIR := "res://assets/audio/piano/"
const CROSSFADE := 3.5
const POOL := 14

var _sfx := {}
var _beds := {}
var _pool: Array[AudioStreamPlayer] = []
var _pool_i := 0
var _music: Array[AudioStreamPlayer] = []
var _active := 0
var _current_bed := &""
var _music_bus := -1
var _sfx_bus := -1
var _reverb: AudioEffectReverb
var _lowpass: AudioEffectLowPassFilter
var _reverb_target := 0.3
var _lp_target := 20000.0
var _last_play := {}
var _piano := {}   # midi -> AudioStream (every 3 semitones from 21)

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_setup_buses()
	for n in SFX_NAMES:
		var p: String = SFX_DIR + n + ".wav"
		if ResourceLoader.exists(p):
			_sfx[n] = load(p)
	for b in BEDS:
		var p: String = MUSIC_DIR + b + ".wav"
		if ResourceLoader.exists(p):
			var s: AudioStream = load(p)
			if s is AudioStreamWAV and (s as AudioStreamWAV).loop_mode == AudioStreamWAV.LOOP_DISABLED:
				var w := s as AudioStreamWAV
				w.loop_mode = AudioStreamWAV.LOOP_FORWARD
				w.loop_begin = 0
				w.loop_end = int(w.get_length() * w.mix_rate)
			_beds[StringName(b)] = s
	for m in range(21, 109, 3):
		var pp := PIANO_DIR + "piano_%d.wav" % m
		if ResourceLoader.exists(pp):
			_piano[m] = load(pp)
	for i in POOL:
		var a := AudioStreamPlayer.new()
		a.bus = &"SFX"
		add_child(a)
		_pool.append(a)
	for i in 2:
		var m := AudioStreamPlayer.new()
		m.bus = &"Music"
		m.volume_db = -80.0
		add_child(m)
		_music.append(m)

func _setup_buses() -> void:
	_music_bus = AudioServer.get_bus_index(&"Music")
	if _music_bus < 0:
		AudioServer.add_bus()
		_music_bus = AudioServer.bus_count - 1
		AudioServer.set_bus_name(_music_bus, &"Music")
		AudioServer.set_bus_send(_music_bus, &"Master")
	_sfx_bus = AudioServer.get_bus_index(&"SFX")
	if _sfx_bus < 0:
		AudioServer.add_bus()
		_sfx_bus = AudioServer.bus_count - 1
		AudioServer.set_bus_name(_sfx_bus, &"SFX")
		AudioServer.set_bus_send(_sfx_bus, &"Master")
	_reverb = AudioEffectReverb.new()
	_reverb.room_size = 0.3
	_reverb.damping = 0.45
	_reverb.wet = 0.18
	_reverb.dry = 1.0
	_reverb.spread = 0.8
	AudioServer.add_bus_effect(_sfx_bus, _reverb)
	_lowpass = AudioEffectLowPassFilter.new()
	_lowpass.cutoff_hz = 20000.0
	AudioServer.add_bus_effect(_music_bus, _lowpass)
	var comp := AudioEffectLimiter.new()
	comp.ceiling_db = -0.5
	AudioServer.add_bus_effect(0, comp)

func apply_volumes(master: float, music: float, sfx: float) -> void:
	AudioServer.set_bus_volume_db(0, _lin_db(master))
	AudioServer.set_bus_volume_db(_music_bus, _lin_db(music))
	AudioServer.set_bus_volume_db(_sfx_bus, _lin_db(sfx))

static func _lin_db(v: float) -> float:
	return -80.0 if v <= 0.001 else linear_to_db(v)

## Play a one-shot. vol in dB, pitch_var = random +- fraction.
func play(name: String, vol: float = 0.0, pitch_var: float = 0.04, pitch: float = 1.0) -> void:
	var s: AudioStream = _sfx.get(name)
	if s == null:
		return
	# Rate-limit identical sounds (coin runs) so they don't stack into mush.
	var now := Time.get_ticks_msec()
	if now - int(_last_play.get(name, -1000)) < 35:
		return
	_last_play[name] = now
	var a := _pool[_pool_i]
	_pool_i = (_pool_i + 1) % _pool.size()
	a.stream = s
	a.volume_db = vol
	a.pitch_scale = pitch * (1.0 + randf_range(-pitch_var, pitch_var))
	a.play()

func set_bed(bed: StringName, instant: bool = false) -> void:
	if bed == _current_bed or not _beds.has(bed):
		return
	_current_bed = bed
	var old := _music[_active]
	_active = 1 - _active
	var nw := _music[_active]
	nw.stream = _beds[bed]
	nw.volume_db = -80.0 if not instant else 0.0
	var trim: float = BED_GAIN.get(bed, 0.0)
	nw.play(randf() * 20.0)
	var tw := create_tween().set_parallel(true)
	var t := 0.05 if instant else CROSSFADE
	tw.tween_method(func(v: float): nw.volume_db = linear_to_db(maxf(v, 0.0001)) + trim, 0.0001 if not instant else 1.0, 1.0, t)
	if old.playing:
		var start := db_to_linear(old.volume_db)
		tw.tween_method(func(v: float): old.volume_db = linear_to_db(maxf(v, 0.0001)), start, 0.0001, t)
		tw.chain().tween_callback(old.stop)

## EE piano block 77: note index n (block rotation) -> MIDI 48 + n (EE's C3 = note 0, like
## SoundManager.playPianoSound(id) = pianoSounds[id + 27] with pianoSounds[0] = A0). Nearest sample, pitch-shifted.
func play_piano(note: int, vol: float = -6.0) -> void:
	if _piano.is_empty():
		return
	var m := clampi(48 + note, 21, 108)
	var base := clampi(21 + int(round((m - 21) / 3.0)) * 3, 21, 108)
	if not _piano.has(base):
		return
	var a := _pool[_pool_i]
	_pool_i = (_pool_i + 1) % _pool.size()
	a.stream = _piano[base]
	a.volume_db = vol
	a.pitch_scale = pow(2.0, (m - base) / 12.0)
	a.play()

func set_room(reverb: float) -> void:
	_reverb_target = reverb

func set_muffled(on: bool) -> void:
	_lp_target = 900.0 if on else 20000.0

func _process(delta: float) -> void:
	if _reverb:
		_reverb.room_size = lerpf(_reverb.room_size, clampf(_reverb_target, 0.0, 0.95), 1.0 - exp(-1.5 * delta))
		_reverb.wet = lerpf(0.08, 0.32, _reverb.room_size)
	if _lowpass:
		_lowpass.cutoff_hz = lerpf(_lowpass.cutoff_hz, _lp_target, 1.0 - exp(-6.0 * delta))
